name: Build

on:
  push:
    branches: [ build ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: build

    strategy:
      matrix:
        os: [macos-11]
        platform: [
            build-mac,
            build-mac-arm,
            build-win
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: ./cmd electron ${{ matrix.platform }}

